### ISSUE TITLE
Верстка повторяющихся элементов сайта

### ISSUE THREAD

**Issue by code-kg** [code-kg/html_group_9_teamwork_team_N3#1]
Introduction
По факту у нас 4 страницы до 9 мая. По одной странице на каждый урок, которые разделены, условно на четыре фазы:
	Phase №1 – 25 апреля – 28 апреля (Тимурлан)
	Phase №2 – 28 апреля – 2 мая (Алима)
	Phase №3 – 2 мая – 5 мая (Ирина)
	Phase №4 – 5 мая – 9 мая (сборка и тестирование)

Phase №1
На данном этапе нам желательно сверстать блоки контента как header, footer и сайдбар на технических страницах, а также подключить Google шрифты, Font Awesome.
Слайдер по усмотрению можно подключить Slick Slider или можно простым скриптом, на выбор.

Время по плану: 4ч
Время по факту:

**Comment by alima-n** [comment]
Сделала header и основной слайдер (на JavaScript, без использования jquery).
