### ISSUE TITLE
Cлайдер

### ISSUE THREAD

**Issue by code-kg** [code-kg/html_group_9_teamwork_team_N3#3]
**Описание задачи:** Сверстать слайдер на техстранице специально создав для этого новую техстраницу или можно в техстраницу №1 который уже есть в репозитории.

**Реализация:**
Можете использовать свой жаваскрипт код или на выбор подключить Слик-Слайдер для ускорения работы.

Время по плану: 2ч
Время по факту: 3ч

**Comment by alima-n** [comment]
Слайдер готов. 
Использован самописный скрипт.

Фактическое время вышло больше, т.к. у слайдера панель управления расположена нестандартно - текст вертикальный.
