### ISSUE TITLE
Верстка сайдбара

### ISSUE THREAD

**Issue by alima-n** [code-kg/html_group_9_teamwork_team_N3#4]
Необходимо сверстать сайдбар на отдельной техстранице, стили добавить в общий style.css

1) Поле поиска с кнопкой типа submit. 
2) Обе картинки-баннера в сайдбаре должны быть кликабельными, с заданным overflow hidden.
3) Список категорий нужно сделать тегом ul, каждая категория - ссылка. 
4) Блок с последними постами - заголовок должен всегда быть в две строки, при большем объеме текста применяется white-space nowrap. Картинка поста и заголовок - ссылками. Нужно подобрать картинки подходящего размера для наглядности.
5) Ссылки на соцсети - иконки Font Awesome. 
6) Для слайдера можно использовать тот же скрипт, что уже есть на странице index.html (только без циклов для dots - индикаторы текущего слайда. В слайдер нужно подобрать 2-3 картинки подходящего размера для наглядности.
7) Плагин Facebook'а вставить картинкой (либо подключить реальный плагин), если останется время от запланированного. 

Планируемое время - 6 часов.

Фактическое время -

**Comment by code-kg** [comment]
Закончил верстку сайдбара, для слайдера использовал слик-слайдер, плагин фейсбук вставлен картинкой.
время по факту - 7ч
