### ISSUE TITLE
Сборка основных страниц

### ISSUE THREAD

**Issue by shmidt8** [code-kg/html_group_9_teamwork_team_N3#7]
1. Сверстать 3 основные страницы путем сборки из типовых блоков.
2. Постараться максимально подогнать под пиксель перфект.
3. Карту в странице contact можно сделать с google map

**Comment by code-kg** [comment]
Изменил позиционирование слайдера с абсолюта на релативный и отрицательным марджином сместил вверх весь блок. При адаптивности .carousel-block img изменил на {width: 100%;} для более адекватного ресайзинга.

**Comment by code-kg** [comment]
Сверстал страницу контактов, вставил карту с google map пуем iframe. Подогнал адаптивность по мере возможности хотя разрешение экрана не позволяет до идеальной пикселеровки. Все страницы сверстаны из типовых блоков.
